version: '2'
services:
#    db:
#      container_name: postgres-db
#      image: 'postgres:11.4'
#      environment:
#        POSTGRES_PASSWORD: password
#        PGDATA: /var/lib/postgresql/data/pgdata
#        TZ: 'Asia/Shanghai'
#      restart: always
#      volumes:
#        - './data.sql:/docker-entrypoint-initdb.d/init.sql'
#        - 'postgres_data:/var/lib/postgresql/data/pgdata'
#      ports:
#        - "5433:5432"
    redis:
      restart: always
      image: redis
      container_name: redis-db
      command: redis-server --bind 0.0.0.0 --requirepass yiyidan52
      ports:
        - "1201:6379"
    rabbitmq:
      image: rabbitmq
      ports:
        - "5672:5672"
        - "15672:15672"
      restart: always
      command:
        - sh
        - -c
        - >
          rabbitmq-server&
          sleep 15&&
          rabbitmqctl add_vhost backend&&
          rabbitmqctl add_vhost broker&&
          rabbitmqctl add_user jamessen 123456&&
          rabbitmqctl set_user_tags jamessen administrator&&
          rabbitmqctl set_permissions -p backend jamessen ".*" ".*" ".*"&&
          rabbitmqctl set_permissions -p broker jamessen ".*" ".*" ".*"&&
          wait
    web:
      container_name: python-3.6
      build:
        context: .
        dockerfile: Dockerfile
      restart: always
      ports:
        - "8000:8000"
        - "8001:8001"
      depends_on:
        - redis
        - rabbitmq
volumes:
  postgres_data: